services:
  # 1. 数据库容器
  db:
    image: postgres:15-alpine
    container_name: erp_postgres_v2
    restart: always
    environment:
      POSTGRES_USER: erp_admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: erp_core_db
      TZ: Asia/Shanghai
    ports:
      - "5435:5432"  # 🟢 如果依然报 5432 占用，请改成 "5435:5432"
    volumes:
    - pgdata:/var/lib/postgresql/data


  # 2. ERP 应用容器
  web:
    build: .
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=erp_admin
      - DB_PASS=admin
      - DB_NAME=erp_core_db
      - TZ=Asia/Shanghai            # 修正时区
      - PYTHONUNBUFFERED=1     
    ports:
      - "8501:8501"
    volumes:
      - ./host_data/uploads:/app/data/uploads 

# 🟢 关键修复：在这里声明上面用到的持久化卷
volumes:
  pgdata: